// @ts-nocheck
// @ts-ignore
import { createContext } from 'react';
// @ts-ignore
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import dynamic from 'next/dynamic'; // Import dynamic from next/dynamic
import ReactQueryProvider from './providers/ReactQueryProvided';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default:"PaperBrock | Complete Solution For Exam ",
    template:"%s | PaperBrock"
  },
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap your application with QueryClientProvider */}

        <ReactQueryProvider>

          <AuthProvider>
            {children}
            <Toaster />
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
